name: Auto-merge PRs

on:
  pull_request_target:
    types: [labeled, opened, reopened, synchronize]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: "contains(github.event.pull_request.labels.*.name, 'automerge')"
    steps:
      - name: Try to auto-merge
        uses: pascalgn/automerge-action@v0.15.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
          # optionally configure required status checks by name
          # required_status_checks: ci
